### ISSUE TITLE
Create the module products

### ISSUE THREAD

**Issue by success77** [KomercoTeam/komerco#4]
I as a client want that this module have the follow items:
>tab products
>tab ingredients
>tab category
>tab stock
>tab stock control
>tab most sold

**Comment by dvillarpsl** [comment]
Se termina el diseño, se realiza un push, por favor verificar con la imagen adjunta, por favor verificar si se debe agregar algo mas @success77 

![screen shot 2017-08-20 at 10 14 11 pm](https://user-images.githubusercontent.com/29414094/29502358-f1442122-85f4-11e7-82fb-e81ba3a6384b.png)

**Comment by success77** [comment]
reviwed.
